table bronze_sales1
	lineageTag: f5fa92bb-6670-4c7c-854c-a14547445189

	measure 'Total Revenue' = SUM(bronze_sales1[Final_Amount])
		lineageTag: 234687ec-68a1-495e-a16f-d94262b8b85c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Measure
		lineageTag: c3c242ca-6dee-4c75-ae32-044e9199ca3b

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Average Revenue' = AVERAGE(bronze_sales1[Final_Amount])
		lineageTag: dbb084e5-1cd8-4b33-aadc-a53de7aae3c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Transaction' = COUNT(bronze_sales1[Sales_ID])
		formatString: 0
		lineageTag: 05eb8fde-29ac-400c-9c11-ac3b31db9caf

	measure 'Total Quantity Sold' = SUM(bronze_sales1[Quantity])
		formatString: 0
		lineageTag: d5393c61-3611-42a4-b93a-7f8edeab3a9e

	measure 'Average Discount' = AVERAGE(bronze_sales1[Discount])
		lineageTag: abd84360-4787-4668-a12b-2b180ffa0f61

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales_ID
		dataType: string
		lineageTag: 758489b4-7f4e-489a-bf26-dd0531f6c94e
		summarizeBy: none
		sourceColumn: Sales_ID

		annotation SummarizationSetBy = Automatic

	column SKU_ID
		dataType: string
		lineageTag: e50fb288-6a31-443f-a32c-03b5d4d10393
		summarizeBy: none
		sourceColumn: SKU_ID

		annotation SummarizationSetBy = Automatic

	column Sale_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5e1508a0-8b4f-49ee-905f-d7a010fa8883
		summarizeBy: none
		sourceColumn: Sale_Date

		variation Variation
			isDefault
			relationship: 949f6503-eef9-4444-9083-46c2fa089cbc
			defaultHierarchy: LocalDateTable_51bbc909-a075-4301-8bc3-7585c223b49f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Store_ID
		dataType: string
		lineageTag: 76718959-c973-4f32-bf5b-182673c718b6
		summarizeBy: none
		sourceColumn: Store_ID

		annotation SummarizationSetBy = Automatic

	column Sales_Channel
		dataType: string
		lineageTag: 28f97a34-2cff-49c0-ade2-28de2e1af8e0
		summarizeBy: none
		sourceColumn: Sales_Channel

		annotation SummarizationSetBy = Automatic

	column Customer_ID
		dataType: string
		lineageTag: 27c4131c-5f05-41a6-8755-bb0aac3cef86
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 28068500-a633-440e-b3fd-870eebdfbd41
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		lineageTag: b78c7bde-1873-4147-acc1-f255033d0da5
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discount
		dataType: double
		lineageTag: fd6dc6c5-c611-42d5-ae9a-6d9bcc78903b
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Final_Amount
		dataType: double
		formatString: #,0
		lineageTag: 28e466a3-f453-4413-9e9b-fadc4c6b947d
		summarizeBy: sum
		sourceColumn: Final_Amount

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Payment_Method
		dataType: string
		lineageTag: 2ddcbfab-c497-4ce6-9889-b8c78613139f
		summarizeBy: none
		sourceColumn: Payment_Method

		annotation SummarizationSetBy = Automatic

	column ingest_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 647926f9-94a3-4965-8b2d-95d22b55da2c
		summarizeBy: none
		sourceColumn: ingest_timestamp

		variation Variation
			isDefault
			relationship: 552dfe79-ff77-4d15-977e-a4932fd142ca
			defaultHierarchy: LocalDateTable_8ac59ed8-0521-4b33-8c9a-2fa9c340596f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition bronze_sales1 = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("dbc-dc58b86b-97ca.cloud.databricks.com", "/sql/1.0/warehouses/68717cf9944c8ae8", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    #"echo_chain_proj-1_Database" = Source{[Name="echo_chain_proj-1",Kind="Database"]}[Data],
				    bronze_Schema = #"echo_chain_proj-1_Database"{[Name="bronze",Kind="Schema"]}[Data],
				    bronze_sales1_Table = bronze_Schema{[Name="bronze_sales1",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(bronze_sales1_Table,{{"Final_Amount", Currency.Type}, {"Sale_Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

